const SPM=(()=>{let authoritativeOffice=null,todayRecord=null;
async function init(){const s=Auth.getSession();if(!s)return;const d=document.getElementById("spm-date");if(d){d.value=UI.todayISO();d.max=UI.todayISO();}await loadUser(s);await loadOffices();bind();await refreshTodayStatus();recalculate();}
async function loadUser(s){try{const r=await Api.getUser(s.userId);if(!r.success||!r.data)throw Error(r.message||"Could not load user profile.");authoritativeOffice={officeId:String(r.data.officeId||"").trim(),officeName:String(r.data.officeName||"").trim()};s.officeId=authoritativeOffice.officeId;s.officeName=authoritativeOffice.officeName;s.name=r.data.name||s.name;s.role=r.data.role||s.role;if(Auth.setSession)Auth.setSession(s);}catch(e){UI.toast(e.message||"Could not load your assigned office.","error");}}
async function loadOffices(){const el=document.getElementById("spm-office");if(!el)return;try{const r=await Api.getOfficeList();const list=r.success?(r.data||[]):[];el.innerHTML='<option value="">Select Office</option>';list.forEach(o=>{const x=document.createElement("option");x.value=o.officeId;x.textContent=o.officeName;el.appendChild(x);});if(authoritativeOffice?.officeId){let x=[...el.options].find(o=>String(o.value)===authoritativeOffice.officeId);if(!x){x=document.createElement("option");x.value=authoritativeOffice.officeId;x.textContent=authoritativeOffice.officeName;el.appendChild(x);}el.value=authoritativeOffice.officeId;el.disabled=true;}}catch(e){UI.toast("Could not load office list.","warning");}}
function bind(){document.getElementById("spm-date")?.addEventListener("change",onChange);document.getElementById("btn-save-draft")?.addEventListener("click",saveDraft);document.getElementById("btn-submit")?.addEventListener("click",submit);document.getElementById("btn-delete-today")?.addEventListener("click",deleteToday);document.getElementById("spm-form")?.addEventListener("input",recalculate);document.getElementById("add-incomplete-set")?.addEventListener("click",()=>addRow("incomplete"));document.getElementById("add-complete-set")?.addEventListener("click",()=>addRow("complete"));}
async function refreshTodayStatus(){if(String(Auth.getSession()?.role||"").toUpperCase()!==CONFIG.ROLES.SPM)return;try{const r=await Api.getOwnTodayRecord();todayRecord=r.success?r.data:null;renderNotice();}catch(e){renderNotice("Could not verify today's submission. Make sure the new Apps Script version is deployed.");}}
function renderNotice(err){let b=document.getElementById("spm-update-notification");if(!b){b=document.createElement("div");b.id="spm-update-notification";b.className="spm-update-notification";document.getElementById("spm-form")?.prepend(b);}if(err){b.className="spm-update-notification spm-notify-warning";b.innerHTML="<strong>⚠ Update status unavailable</strong><span>"+esc(err)+"</span>";return;}if(!todayRecord){b.className="spm-update-notification spm-notify-pending";b.innerHTML='<strong>🔔 PMV Toolkit Update Pending</strong><span>Today\\'s PMV Toolkit information has not been updated yet.</span>';return;}b.className="spm-update-notification spm-notify-complete";b.innerHTML='<strong>🟢 Today\\'s update is submitted</strong><span>You may edit the form or delete today\\'s entry before submitting again.</span><button type="button" id="spm-delete-today-now" class="danger">DELETE TODAY\\'S ENTRY</button>';document.getElementById("spm-delete-today-now")?.addEventListener("click",deleteToday);}
async function deleteToday(){if(!todayRecord){UI.toast("No entry for today was found.","info");return;}const ok=await UI.confirmModal("Delete Today's Entry","This deletes ALL of your DAILY_DATA rows for today, including duplicate rows. You can then submit one fresh entry.","DELETE TODAY");if(!ok)return;try{const r=await Api.deleteOwnTodayRecord(todayRecord.id);if(!r.success){UI.toast(r.message||"Could not delete today's entry.","error");return;}todayRecord=null;renderNotice();UI.toast("Today's entry deleted. You can submit again.","success");}catch(e){UI.toast(e.message||"Delete failed. Deploy the new Apps Script version.","error");}}
async function onChange(){const d=document.getElementById("spm-date")?.value;if(d===UI.todayISO())await refreshTodayStatus();const o=authoritativeOffice?.officeId;if(o&&d)try{const r=await Api.getPreviousDay(o,d),x=r.success?r.data:null;UI.setText("prev-came",x?x.kitsCameToday:"—");UI.setText("prev-delivered",x?x.kitsDelivered:"—");UI.setText("prev-redirected",x?x.redirected:"—");UI.setText("prev-pending",x?x.currentPending:"—");}catch(e){}}
function addRow(kind){const inc=kind==="incomplete",c=document.getElementById(inc?"incomplete-rows":"complete-rows");if(!c)return;const n=c.querySelectorAll(".set-row").length+1,q=inc?"kitsIncomplete":"kitsComplete",r=document.createElement("div");r.className="set-row";r.innerHTML='<div class="set-row-header">Set '+n+'</div><div class="field-group"><label>Set Number</label><input type="number" class="set-number"></div><div class="field-group"><label>'+(inc?"Kits Incomplete":"Kits Complete")+'</label><input type="number" min="0" class="'+q+'"></div>';c.appendChild(r);}
function rows(kind){const inc=kind==="incomplete",c=document.getElementById(inc?"incomplete-rows":"complete-rows"),q=inc?"kitsIncomplete":"kitsComplete";return c?[...c.querySelectorAll(".set-row")].map(r=>({setNumber:r.querySelector(".set-number")?.value||"",[q]:Number(r.querySelector("."+q)?.value)||0})):[];}
function data(){const s=Auth.getSession(),o=document.getElementById("spm-office");return{date:document.getElementById("spm-date")?.value||UI.todayISO(),officeId:authoritativeOffice?.officeId||o?.value||"",officeName:authoritativeOffice?.officeName||o?.selectedOptions?.[0]?.textContent||"",spmId:s.userId,spmName:s.name,kitsCameToday:v("kits-came"),kitsDelivered:v("kits-delivered"),redirected:v("redirected"),mobileInvalid:v("mobile-invalid"),addressNotFound:v("address-not-found"),torn:v("torn-condition"),incompleteRows:rows("incomplete"),completeRows:rows("complete")};}
function recalculate(){const d=data(),p=Calculations.calculateTotalPending({mobileInvalid:d.mobileInvalid,addressNotFound:d.addressNotFound,torn:d.torn,incompleteRows:d.incompleteRows,completeRows:d.completeRows}),pct=Calculations.calculateDeliveryPercent(d.kitsDelivered,d.kitsCameToday);UI.setText("total-incomplete",Calculations.sumIncompleteKits(d.incompleteRows));UI.setText("total-complete",Calculations.sumCompleteKits(d.completeRows));UI.setText("total-pending",p);UI.setText("delivery-percent",pct.toFixed(1)+"%");return{totalPending:p,deliveryPct:pct};}
async function saveDraft(){const d=data();if(!d.officeId)return UI.toast("Office is not loaded from USER_MASTER.","warning");await Storage.saveDraft(d.date,d.officeId,d);UI.toast("Draft saved on this device.","success");}
async function submit(){const d=data(),vld=Validation.validateDailyRecord(d);if(!vld.valid)return UI.toast(vld.errors[0],"error");const t=recalculate();const ok=await UI.confirmModal("Confirm Submission","Office: <b>"+esc(d.officeName)+"</b><br>Pending: <b>"+t.totalPending+"</b><br>Delivery: <b>"+t.deliveryPct.toFixed(1)+"%</b>","CONFIRM & SYNC");if(!ok)return;const rec={id:(d.date+"_"+d.officeId+"_"+(crypto.randomUUID?.()||Date.now())),...d,totalPending:t.totalPending,deliveryPercentage:t.deliveryPct,submittedAt:new Date().toISOString()};try{const r=await Api.submitDailyRecord(rec,Auth.getSession());if(r.success){await Storage.clearDraft(d.date,d.officeId);await refreshTodayStatus();UI.toast("Today's update submitted successfully.","success");}else if(r.code==="DUPLICATE"){await refreshTodayStatus();UI.toast("Duplicate blocked. Delete today's existing entry first.","warning",6000);}else UI.toast(r.message||"Submission rejected.","error");}catch(e){UI.toast(e.message||"Submission failed.","error");}}
function v(id){return document.getElementById(id)?.value||""}function esc(x){return String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));}
return{init,recalculate,refreshTodayStatus};})();
