const SPM=(()=>{let authoritativeOffice=null,todayRecord=null;
async function init(){const s=Auth.getSession();if(!s)return;const d=document.getElementById("spm-date");if(d){d.value=UI.todayISO();d.max=UI.todayISO();}
await loadUser(s);await loadOffices();bind();await refreshTodayStatus();recalculate();}
async function loadUser(s){try{const r=await Api.getUser(s.userId);if(!r.success||!r.data)throw Error(r.message||"Could not load user profile.");authoritativeOffice={officeId:String(r.data.officeId||"").trim(),officeName:String(r.data.officeName||"").trim()};s.officeId=authoritativeOffice.officeId;s.officeName=authoritativeOffice.officeName;s.name=r.data.name||s.name;s.role=r.data.role||s.role;if(Auth.setSession)Auth.setSession(s);}catch(e){authoritativeOffice=null;UI.toast(e.message||"Could not load assigned office.","error");}}
async function loadOffices(){const el=document.getElementById("spm-office");if(!el)return;try{const r=await Api.getOfficeList(),list=r.success?(r.data||[]):[];el.innerHTML='<option value="">Select Office</option>';list.forEach(o=>{const x=document.createElement("option");x.value=o.officeId;x.textContent=o.officeName;el.appendChild(x);});if(String(Auth.getSession()?.role||"").toUpperCase()===CONFIG.ROLES.SPM){if(!authoritativeOffice?.officeId){el.value="";el.disabled=true;return;}let x=[...el.options].find(o=>String(o.value)===authoritativeOffice.officeId);if(!x){x=document.createElement("option");x.value=authoritativeOffice.officeId;x.textContent=authoritativeOffice.officeName||authoritativeOffice.officeId;el.appendChild(x);}el.value=authoritativeOffice.officeId;el.disabled=true;el.title="Office is assigned by Admin and cannot be changed.";}}catch(e){UI.toast("Could not load office list.","warning");}}
function bind(){document.getElementById("spm-date")?.addEventListener("change",onChange);const o=document.getElementById("spm-office");if(o&&!o.disabled)o.addEventListener("change",onChange);document.getElementById("add-incomplete-set")?.addEventListener("click",()=>addRow("incomplete"));document.getElementById("add-complete-set")?.addEventListener("click",()=>addRow("complete"));document.getElementById("btn-save-draft")?.addEventListener("click",saveDraft);document.getElementById("btn-submit")?.addEventListener("click",submit);document.getElementById("btn-delete-today")?.addEventListener("click",deleteToday);document.getElementById("spm-form")?.addEventListener("input",recalculate);}
async function refreshTodayStatus(){if(String(Auth.getSession()?.role||"").toUpperCase()!==CONFIG.ROLES.SPM)return;try{const r=await Api.getOwnTodayRecord(Auth.getSession());todayRecord=r.success?r.data:null;notify();}catch(e){notify("Could not verify today's submission status.");}}
function notify(err){let b=document.getElementById("spm-update-notification");if(!b){b=document.createElement("div");b.id="spm-update-notification";b.className="spm-update-notification";(document.getElementById("spm-form")||document.body).prepend(b);}
if(err){b.className="spm-update-notification spm-notify-warning";b.innerHTML=`<strong>⚠ Update status unavailable</strong><span>${esc(err)}</span>`;return;}
if(!todayRecord){b.className="spm-update-notification spm-notify-pending";b.innerHTML=`<strong>🔔 PMV Toolkit Update Pending</strong><span>Today's PMV Toolkit information has not been updated yet.</span><button type="button" id="spm-notify-update">Update Now</button>`;document.getElementById("spm-notify-update")?.addEventListener("click",()=>document.getElementById("spm-form")?.scrollIntoView({behavior:"smooth"}));return;}
b.className="spm-update-notification spm-notify-complete";b.innerHTML=`<strong>🟢 Today's PMV Toolkit update is submitted</strong><span>Submitted ${esc(todayRecord.submittedAt||todayRecord.updatedAt||"recently")}.</span><button type="button" id="spm-edit-today">Edit Today's Entry</button><button type="button" id="spm-delete-today" class="danger">Delete Today's Entry</button>`;document.getElementById("spm-edit-today")?.addEventListener("click",()=>document.getElementById("spm-form")?.scrollIntoView({behavior:"smooth"}));document.getElementById("spm-delete-today")?.addEventListener("click",deleteToday);}
async function deleteToday(){if(!todayRecord)return;const ok=await UI.confirmModal("Delete Today's Entry","Only your own entry for today will be deleted. You can submit again afterwards.","DELETE TODAY");if(!ok)return;try{const r=await Api.deleteOwnTodayRecord(Auth.getSession(),todayRecord.id);if(!r.success){UI.toast(r.message||"Could not delete today's entry.","error");return;}todayRecord=null;notify();UI.toast("Today's entry deleted. You can submit again.","success");}catch(e){UI.toast(e.message||"Could not delete today's entry.","error");}}
async function onChange(){const o=document.getElementById("spm-office")?.value,d=document.getElementById("spm-date")?.value;if(!o||!d)return;try{const r=await Api.getPreviousDay(o,d),x=r.success?r.data:null;UI.setText("prev-came",x?x.kitsCameToday:"—");UI.setText("prev-delivered",x?x.kitsDelivered:"—");UI.setText("prev-redirected",x?x.redirected:"—");UI.setText("prev-pending",x?x.currentPending:"—");}catch(e){}if(d===UI.todayISO())await refreshTodayStatus();}
function addRow(kind){const inc=kind==="incomplete",c=document.getElementById(inc?"incomplete-rows":"complete-rows");if(!c)return;const n=c.querySelectorAll(".set-row").length+1,q=inc?"kitsIncomplete":"kitsComplete";const r=document.createElement("div");r.className="set-row";r.innerHTML=`<div class="set-row-header">Set ${n}</div><div class="field-group"><label>Set Number</label><input type="number" class="set-number"></div><div class="field-group"><label>${inc?"Kits Incomplete":"Kits Complete"}</label><input type="number" min="0" class="${q}"></div>${n>1?'<button type="button" class="btn-remove-row">✕ Remove</button>':""}`;r.querySelector(".btn-remove-row")?.addEventListener("click",()=>{r.remove();recalculate();});c.appendChild(r);}
function rows(kind){const inc=kind==="incomplete",c=document.getElementById(inc?"incomplete-rows":"complete-rows"),q=inc?"kitsIncomplete":"kitsComplete";return c?[...c.querySelectorAll(".set-row")].map(r=>({setNumber:r.querySelector(".set-number")?.value||"",[q]:Number(r.querySelector("."+q)?.value)||0})):[];}
function data(){const s=Auth.getSession(),o=document.getElementById("spm-office");return{date:document.getElementById("spm-date")?.value||UI.todayISO(),officeId:authoritativeOffice?.officeId||o?.value||"",officeName:authoritativeOffice?.officeName||o?.selectedOptions?.[0]?.textContent||"",spmId:s.userId,spmName:s.name,kitsCameToday:v("kits-came"),kitsDelivered:v("kits-delivered"),redirected:v("redirected"),mobileInvalid:v("mobile-invalid"),addressNotFound:v("address-not-found"),torn:v("torn-condition"),incompleteRows:rows("incomplete"),completeRows:rows("complete"),previousCurrentPending:v("spm-prev-pending-hidden")||0};}
function recalculate(){const d=data(),p=Calculations.calculateTotalPending({mobileInvalid:d.mobileInvalid,addressNotFound:d.addressNotFound,torn:d.torn,incompleteRows:d.incompleteRows,completeRows:d.completeRows}),pct=Calculations.calculateDeliveryPercent(d.kitsDelivered,d.kitsCameToday);UI.setText("total-incomplete",Calculations.sumIncompleteKits(d.incompleteRows));UI.setText("total-complete",Calculations.sumCompleteKits(d.completeRows));UI.setText("total-pending",p);UI.setText("delivery-percent",pct.toFixed(1)+"%");return{totalPending:p,deliveryPct:pct};}
async function saveDraft(){const d=data();if(!d.date||!d.officeId){UI.toast("Select date and office.","warning");return;}await Storage.saveDraft(d.date,d.officeId,d);UI.toast("Draft saved on this device.","success");}
async function submit(){const d=data(),val=Validation.validateDailyRecord(d);if(!val.valid){UI.toast(val.errors[0],"error");return;}const t=recalculate(),ok=await UI.confirmModal("Confirm Submission",`Office: <b>${esc(d.officeName)}</b><br>Pending: <b>${t.totalPending}</b><br>Delivery: <b>${t.deliveryPct.toFixed(1)}%</b>`,"CONFIRM & SYNC");if(!ok)return;const rec={id:`${d.date}_${d.officeId}_${crypto.randomUUID?.()||Date.now()}`,...d,totalPending:t.totalPending,deliveryPercentage:t.deliveryPct,submittedAt:new Date().toISOString()};try{const r=await Api.submitDailyRecord(rec,Auth.getSession());if(r.success){await Storage.clearDraft(d.date,d.officeId);await refreshTodayStatus();UI.toast("Today's update submitted successfully.","success");}else if(r.code==="DUPLICATE"){await refreshTodayStatus();UI.toast("Today's entry already exists. Use Edit or Delete Today's Entry.","warning",6000);}else UI.toast(r.message||"Submission rejected.","error");}catch(e){await Storage.queueForSync(rec);UI.toast("Network issue. Entry queued for sync.","warning");}}
function v(id){return document.getElementById(id)?.value||"";}function esc(x){return String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));}
return{init,recalculate,refreshTodayStatus};})();